### ISSUE TITLE
ELY09508: Cannot write credential to store ELY08028: Invalid algorithm "clear"

### ISSUE THREAD

**Issue by losmurfs** [wildfly-security/wildfly-elytron-tool#184]
How do I tell it to not use the "clear" algorithm that I don't want to use?
D:\wildfly\wildfly-26.0.0.Final>bin\elytron-tool.bat credential-store --create --location=credentials\rmstore.jceks --type KeyStoreCredentialStore
Credential store password:
Confirm credential store password:
Credential Store has been successfully created
D:\wildfly\wildfly-26.0.0.Final>bin\elytron-tool.bat credential-store --location credentials\rmstore.jceks --add rmbm --debug
Credential store password:
Secret to store:
Confirm secret to store:
Exception encountered executing the command:
org.wildfly.security.credential.store.CredentialStoreException: ELY09508: Cannot write credential to store
        at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.credential.store.impl.KeyStoreCredentialStore.store(KeyStoreCredentialStore.java:413)
        at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.credential.store.CredentialStore.store(CredentialStore.java:242)
        at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.credential.store.CredentialStore.store(CredentialStore.java:226)
        at org.wildfly.security.elytron-tool@1.18.1.Final//org.wildfly.security.tool.CredentialStoreCommand.addAlias(CredentialStoreCommand.java:510)
        at org.wildfly.security.elytron-tool@1.18.1.Final//org.wildfly.security.tool.CredentialStoreCommand.execute(CredentialStoreCommand.java:421)
        at org.wildfly.security.elytron-tool@1.18.1.Final//org.wildfly.security.tool.ElytronTool.main(ElytronTool.java:84)
        at org.jboss.modules.Module.run(Module.java:353)
        at org.jboss.modules.Module.run(Module.java:321)
        at org.jboss.modules.Main.main(Main.java:604)
Caused by: java.security.NoSuchAlgorithmException: ELY08028: Invalid algorithm "clear"
        at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.password.PasswordFactory.getInstance(PasswordFactory.java:123)
        at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.credential.store.impl.KeyStoreCredentialStore.store(KeyStoreCredentialStore.java:287)
        ... 8 more

**Comment by fjuma** [comment]
@losmurfs This is a bug that will be fixed in an upcoming release (see https://issues.redhat.com/browse/WFCORE-5764 for details).

To work around the problem for now, you can update your `$WILDFLY_HOME/modules/system/layers/base/org/wildfly/security/elytron-tool/main/module.xml` file to add `services="import"` to the `elytron-private` module dependency as follows:

```
<module name="org.wildfly.security.elytron-private" services="import"/>
```

**Comment by losmurfs** [comment]
That worked, thank you!
